### ISSUE TITLE
Update README with links to other nullability discussions and RFCs

### ISSUE THREAD

**Issue by twof** [graphql/nullability-wg#38]
- assignee(s): @twof  
- source: https://docs.google.com/document/d/1IwWB_JBgqFnKVNnXph1k0j3ZTrMzYR9n8fEaxR11Fj4/edit#heading=h.3axi4ijsf22i 

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by fotoetienne** [comment]
Presumed Done
